### PR TITLE
Fix SIMPLEX_CAVES not having a config file

### PR DESCRIPTION
**Pull request by yavincl**

### CODE REVIEW

**Review by jaskarth — CHANGES_REQUESTED** [review]
This change would use the erosion config data for caves. Because of that, I cannot accept this change. I will do this soon myself, don't worry.

**Comment by yavincl** [comment]
ₒₒₚₛ
i copy pasted it xd

**Comment by yavincl** [comment]
Fortunately, seems you already wrote a caveconfigdata class.

**Comment by jaskarth** [comment]
Unfortunately, just adding that line won't do anything as it's not hooked up anywhere. I'm closing this PR for now, I'll be able to handle it ;)

**Pull request closed without merging**
